CC = gcc
CFLAGS = -Wall -Wextra -O2
OBJS = main.o board.o capture.o readArc.o
TARGET = tp1

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS)

main.o: main.c board.h capture.h readArc.h
board.o: board.c board.h
capture.o: capture.c board.h capture.h
readArc.o: board.h readArc.c

clean:
	rm -f $(OBJS) $(TARGET)
