CC = gcc
CFLAGS = -Wall -Wextra -O2
OBJS = main.o readArc.o
TARGET = tp1

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS)

main.o: main.c readArc.h
readArc.o: readArc.o readArc.h

clean:
	rm -f $(OBJS) $(TARGET)
